"""
This is NOT a full settings.py -- it's the block of settings specific to
this project that you paste into the settings.py generated by
`django-admin startproject config .`

Full setup steps are in README_SETUP.md.
"""

import os
from datetime import timedelta

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "accounts",
    "core",
    "fleet",
    "drivers",
    "trips",
    "maintenance",
    "finance",
    "analytics",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # must be high in the list
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Dev only -- lock this down before any real deployment
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    # Throttle login attempts so brute-forcing isn't trivial -- separate
    # from the 5-attempt account lockout, this caps requests per IP too.
    "DEFAULT_THROTTLE_CLASSES": ("rest_framework.throttling.ScopedRateThrottle",),
    "DEFAULT_THROTTLE_RATES": {"login": "10/min"},
}

# Google Sign-In: create a Client ID at https://console.cloud.google.com
# (APIs & Services -> Credentials -> OAuth client ID -> Web application).
# Free, no billing account required for this.
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),  # generous for an 8hr hackathon demo
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Currency & Units (System-Wide Global Architecture requirement)
DEPOT_DEFAULTS = {
    "CURRENCY": "INR",
    "DISTANCE_UNIT": "km",
    "WEIGHT_UNIT": "kg",
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "transitops"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# If Postgres setup eats too much hackathon time, swap DATABASES for:
# DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}

# Simple in-memory cache is enough for dashboard KPI caching in a hackathon.
# Swap for Redis (django-redis) if you have time and want it to survive
# server restarts / work across multiple worker processes.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}
