# Generated by Django 5.0.6 on 2026-07-12 05:07

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('trip_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('source', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Driving duration in seconds from OSRM. Used for ETA calculation.', null=True)),
                ('routing_source', models.CharField(choices=[('manual', 'Manual entry'), ('osrm', 'OSRM (real routing)')], default='manual', help_text='Indicates whether planned_distance_km came from OSRM or was typed manually.', max_length=16)),
                ('final_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_consumed_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', django_fsm.FSMField(choices=[('Draft', 'Draft'), ('Dispatched', 'Dispatched'), ('In-Transit', 'In-Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50, protected=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
