# Generated by Django 5.0.6 on 2026-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_acquisition_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_load_capacity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
